const CART_TYPES = {
    TOGGLE_CART_HIDE: 'TOGGLE_CART_HIDE',
    ADD_ITEMS : 'ADD_ITEM',
    REMOVE_ALL_ITEM : 'REMOVE_ALL_ITEM',
    REMOVE_ITEM : 'REMOVE_ITEM',
    CLEAR_CART: 'CLEAR_CART'
}

export default CART_TYPES